@Api_HostAddress = http://localhost:5188

GET {{Api_HostAddress}}/api/v1/weather/forecast/
Accept: application/json

###

GET {{Api_HostAddress}}/api/v1/weather/summary/
Accept: application/json

###
